require 'dep_selector/dependency_graph'
require 'dep_selector/package'
require 'dep_selector/package_version'
require 'dep_selector/dependency'
require 'dep_selector/objective_function'
require 'dep_selector/version_constraint'
